#!/bin/sh
. /home/kpanel.conf
if [ ! -f /etc/php.d/opcache.ini ]; then
clear
echo "========================================================================="
echo "Zend Opcache dang duoc TAT"
echo "-------------------------------------------------------------------------"
echo "Hay bat Zend Opcache len de su dung chuc nang nay"
/etc/kpanel/menu/opcache/kpanel-before-opcache
else
echo "-------------------------------------------------------------------------"
echo "Please wait..."; sleep 1
clear
echo "========================================================================="
echo "Su Dung Link Duoi Day De Xem Zend Opcache Status:"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/ocp.php"
/etc/kpanel/menu/opcache/kpanel-before-opcache
fi
