#!/bin/sh
. /home/kpanel.conf
prompt="Lua chon cua ban (0-Thoat):"
options=("Bat Zend Opcache" "Cau Hinh Zend Opcache" "Them Website Vao BlackList" "Xoa Website Khoi Blacklist" "Clear Zend OPcache")
printf "=========================================================================\n"
printf "                kpanel - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                          Zend OPcache Manage \n"
printf "=========================================================================\n"
printf "                    Zend Opcache Current: Disable\n"
printf "=========================================================================\n"
printf "Zend Opcache Manage Link: http://$serverip:$priport/ocp.php\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
	1 ) /etc/kpanel/menu/opcache/kpanel-bat-opcache;;
	2 ) /etc/kpanel/menu/opcache/kpanel-opcache-change-size;;
	3) /etc/kpanel/menu/opcache/kpanel-them-website-vao-blacklist;;
	4) /etc/kpanel/menu/opcache/kpanel-xoa-website-khoi-blacklist;;
	5) /etc/kpanel/menu/opcache/kpanel-clear-opcache;;
	#$(( ${#options[@]}+1 )) ) echo "";  clear && /bin/kpanel;;
	0) echo "";  clear && /bin/kpanel;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;

    esac
done
