#!/bin/bash
. /home/kpanel.conf
rm -rf /tmp/*kdatavn*
mkdir -p /tmp/sitedangbatpagespeedkdatavn
ls /etc/nginx/conf.d > /tmp/kpanel-websitelist
sed -i 's/\.conf//g' /tmp/kpanel-websitelist 
sowebsitetrenserver=$(cat /tmp/kpanel-websitelist | wc -l)
websitetrenserver=$(cat /tmp/kpanel-websitelist)
for website in $websitetrenserver 
do
if [ "$(grep "ngx_pagespeed.conf" /etc/nginx/conf.d/$website.conf)" == "include /etc/nginx/ngx_pagespeed.conf;" ]; then
touch /tmp/sitedangbatpagespeedkdatavn/$website
fi
done
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 1
clear
echo "========================================================================="
echo "Website tren server: $sowebsitetrenserver"
echo "-------------------------------------------------------------------------"
if [ "$(ls -1 /tmp/sitedangbatpagespeedkdatavn | wc -l)" == "0" ]; then
echo "Website Enabled Nginx Pagespeed: 0"
else
echo "Website dang Bat Nginx Pagespeed: $(ls -1 /tmp/sitedangbatpagespeedkdatavn | wc -l)"
echo "-------------------------------------------------------------------------"
ls /tmp/sitedangbatpagespeedkdatavn | pr -3 -t
fi
rm -rf /tmp/*kdatavn*
rm -rf /tmp/*kpanel*
/etc/kpanel/menu/pagespeed/kpanel-pagespeed-menu

