#!/bin/sh
prompt="Nhap lua chon cua ban (0-Thoat):"
options=("Enable Nginx Pagespeed" "Disable Nginx Pagespeed" "Clear Nginx Pagespeed Cache" "List Website BAT Nginx Pagespeed")

printf "=========================================================================\n"
printf "                kpanel - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                         Quan Ly Nginx Pagespeed                                \n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    1 ) /etc/kpanel/menu/pagespeed/kpanel-bat-pagespeed;;
    2 ) /etc/kpanel/menu/pagespeed/kpanel-tat-pagespeed;;
    3 ) /etc/kpanel/menu/pagespeed/kpanel-clear-pagespeed;;
    4 ) /etc/kpanel/menu/pagespeed/kpanel-list-website-dang-bat-pagespeed;;
    
    $(( ${#options[@]}+1 )) ) echo "bye!";  clear && /bin/kpanel;;
    0 ) echo "bye!";  clear && /bin/kpanel;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac
done
