#!/bin/sh
. /home/kpanel.conf
rm -rf /tmp/*kdatavn*
mkdir -p /tmp/saoluuwebsitethanhcongkdatavn
mkdir -p /tmp/saoluuwebsitethatbaikdatavn
ls /etc/nginx/conf.d > /tmp/kpanel-websitelist
sed -i 's/\.conf//g' /tmp/kpanel-websitelist 
 cat > "/tmp/kpanel-replace" <<END
sed -i '/$mainsite/d' /tmp/kpanel-websitelist
END
chmod +x /tmp/kpanel-replace
/tmp/kpanel-replace
rm -rf /tmp/kpanel-replace
rm -rf /tmp/checksite-list
sowebsitetrenserver=$(cat /tmp/kpanel-websitelist | wc -l)
listwebsite=$(cat /tmp/kpanel-websitelist)
rm -rf /tmp/checksite-list
for checksite in $listwebsite 
do
if [ -f /home/$checksite/public_html/index.php ]; then
echo "$checksite" >> /tmp/checksite-list
fi
 done

if [ ! -f /tmp/checksite-list ]; then
rm -rf /tmp/*kpanel*
rm -rf /tmp/*kdatavn*
clear
echo "========================================================================="
echo "Khong tim thay website co du lieu tren server"
/etc/kpanel/menu/3_backup-restore/kpanel-sao-luu
fi
prompt="Nhap lua chon cua ban :"
options=("BAT/TAT Tu Dong Backup Website" "List Website BAT Tu Dong Backup")
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    1 ) /etc/kpanel/menu/3_backup-restore/kpanel-befor-chon-tat-bat-tu-dong-sao-luu-code;;
    2 ) /etc/kpanel/menu/3_backup-restore/kpanel-danh-sach-website-tu-dong-sao-luu-code;;
    $(( ${#options[@]}+1 )) ) echo "";  clear && /etc/kpanel/menu/3_backup-restore/kpanel-sao-luu;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;

    esac
done
