#!/bin/sh

cd ~
if [ -d /opt/kdata_kpanel ]; then
rm -rf /opt/kdata_kpanel/*
rm -rf /opt/kdata_kpanel
sleep 2
fi

sudo yum -y install wget

#
cd ~
wget --no-check-certificate -q https://raw.githubusercontent.com/kdatavn/kpanel-version-2/main/script/kpanel/menu/git-clone
chmod +x /root/git-clone
bash /root/git-clone

cd /opt/kdata_kpanel
chmod +x setup
bash setup
