#!/bin/sh

if [ $(id -u) != "0" ]; then
    echo "Co loi: Ban phai dang nhap bang user root!"
    exit
fi

if [ -f /var/cpanel/cpanel.config ]; then
echo "Server cua ban da cai san WHM/Cpanel, neu ban muon dung KPANEL"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/psa/.psa.shadow ]; then
echo "Server cua ban da cai san Plesk, neu ban muon dung KPANEL"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/init.d/directadmin ]; then
echo "Server cua ban da cai san DirectAdmin, neu ban muon dung KPANEL"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /etc/init.d/webmin ]; then
echo "Server cua ban da cai san webmin, neu ban muon dung KPANEL"
echo "Hay cai moi lai he dieu hanh, khuyen dung centos6 - 64bit"
echo "Chao tam biet !"
exit
fi

if [ -f /home/kpanel.conf ]; then
clear
echo "========================================================================="
echo "========================================================================="
echo "Server/VPS cua ban da cai san KPANEL"
echo "Hay su dung lenh KPANEL de truy cap KPANEL menu"
echo "Chao tam biet !"
echo "========================================================================="
echo "========================================================================="
rm -rf install*
exit
fi

arch=`uname -m`
if [ ! "$arch" = "x86_64" ]; then
clear
echo "========================================================================="
echo "========================================================================="
echo "Hien tai! KPANEL chi ho tro phien ban x64 bit"
echo "Vui long cai dat phien ban he dieu hanh x86_64 roi thu lai"
echo "Chao tam biet !"
echo "========================================================================="
echo "========================================================================="
rm -rf install*
exit
fi

if [ -f /etc/yum.repos.d/epel.repo ]; then
sudo sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
fi

#wget -q https://kpanel.echbay.com/script/kpanel/calc -O /bin/calc && chmod +x /bin/calc
yes | cp -rf /opt/vps_kdata/script/kpanel/calc /bin/calc && chmod +x /bin/calc
clear  
rm -rf /root/kpanel*

#prompt="Nhap lua chon cua ban: "
#options=("Tieng Viet" "Tieng Anh" "Huy Bo")
echo "========================================================================="
echo "KPANEL Ho Tro Centos 6 & Centos 7 & Centos 8 x64"
echo "-------------------------------------------------------------------------"
echo "Ban nen su dung Centos 7 x64 de Server co hieu suat tot nhat."
echo "-------------------------------------------------------------------------"
#echo "KPANEL ho tro 2 ngon ngu: Tieng Anh va Tieng Viet. "
#echo "-------------------------------------------------------------------------"
#echo "Trong qua trinh su dung, ban co the thay doi ngon ngu ngon ngu bang chuc "
#echo "-------------------------------------------------------------------------"
#echo "nang [ Change KPANEL Language ] trong [ Update System ]."
#echo "========================================================================="
#echo "                   Chon Ngon Ngu Cho KPANEL"
echo "========================================================================="

#PS3="$prompt"
#select opt in "${options[@]}"; do 
#case "$REPLY" in
#1) yourlanguage="vietnamese"; break;;
#2) yourlanguage="english"; break;;
#3) yourlanguage="Cancel"; break;;
#*) echo "Ban nhap sai, vui long nhap theo so thu tu trong danh sach";continue;;
#esac  
#done
yourlanguage="vietnamese"

current_os_version=$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))
#echo $current_os_version

cd ~

if [ "$yourlanguage" = "english" ]; then
echo "----------------------------------------------------------------------------"
echo "Please wait ..."
sleep 2
#wget -q --no-check-certificate https://kpanel.com/script/kpanel/centos${current_os_version}/kpanel-setup && chmod +x kpanel-setup && clear && ./kpanel-setup
#wget -q --no-check-certificate https://kpanel.echbay.com/script/kpanel/centos${current_os_version}/kpanel-setup && chmod +x kpanel-setup && clear && ./kpanel-setup
cd /opt/vps_kdata/script/kpanel/centos${current_os_version} ; chmod +x kpanel-setup ; clear ; bash kpanel-setup
yes | cp -rf /opt/vps_kdata/script/kpanel/centos${current_os_version}/kpanel-setup ~/kpanel-setup ; chmod +x kpanel-setup ; clear ; bash kpanel-setup
elif [ "$yourlanguage" = "vietnamese" ]; then
echo "----------------------------------------------------------------------------"
echo "Please wait ..."
sleep 2
#wget -q --no-check-certificate https://kpanel.echbay.com/script/kpanel/centos${current_os_version}/kpanel-setup && chmod +x kpanel-setup && clear && ./kpanel-setup
if [ "$current_os_version" == "6" ]; then
#cd /opt/vps_kdata/script/kpanel/centos6 ; chmod +x kpanel-setup ; clear ; bash kpanel-setup
yes | cp -rf /opt/vps_kdata/script/kpanel/centos6/kpanel-setup ~/kpanel-setup ; chmod +x kpanel-setup ; clear ; bash kpanel-setup
elif [ "$current_os_version" == "7" ]; then
#cd /opt/vps_kdata/script/kpanel/centos7 ; chmod +x kpanel-setup ; clear ; bash kpanel-setup
yes | cp -rf /opt/vps_kdata/script/kpanel/centos7/kpanel-setup ~/kpanel-setup ; chmod +x kpanel-setup ; clear ; bash kpanel-setup
else
#cd /opt/vps_kdata/script/kpanel/centos8 ; chmod +x kpanel-setup ; clear ; bash kpanel-setup
yes | cp -rf /opt/vps_kdata/script/kpanel/centos8/kpanel-setup ~/kpanel-setup ; chmod +x kpanel-setup ; clear ; bash kpanel-setup
fi
else 
rm -rf /root/install* && rm -rf /root/kpanel* && clear
fi


