#!/bin/bash 

. /home/kpanel.conf

prompt="Nhap lua chon cua ban: "
options=( "1 Database" "Tat Ca Database" "Huy Bo")
printf "=========================================================================\n"
printf "LUA CHON LAY LINK DOWNLOAD FILE BACKUP 1 DATABASE HAY TAT CA CAC DATABASE  \n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) laylink="1database"; break;;
    2) laylink="tatca"; break;;
    3) laylink="cancle"; break;;
    *) echo "Ban nhap sai ! Ban vui long chon so trong danh sach";continue;;
    esac  
done
###################################
#
###################################
if [ "$laylink" = "1database" ]; then
/etc/kpanel/menu/4_database/kpanel-link-database-sao-luu
###################################
#
###################################
elif [ "$laylink" = "tatca" ]; then
/etc/kpanel/menu/4_database/kpanel-link-download-tat-ca-backup-database-sao-luu
###################################
#
###################################
else 
clear && /etc/kpanel/menu/4_database/kpanel-them-xoa-database
fi
