#!/bin/sh
. /home/kpanel.conf
if [ ! -f /etc/kpanel/btsync.info ]; then
clear
echo "========================================================================= "
echo "Ban chua cai dat BTsync"
/etc/kpanel/menu/17_bitsync/kpanel-bitsync-menu
else
echo "Please wait..."; sleep 1
clear
echo "========================================================================="
echo "Thong tin quan ly BTsync:"
echo "-------------------------------------------------------------------------"
echo "Link truy cap: http://$serverip:$(grep btport /etc/kpanel/btsync.info | awk 'NR==1 {print $3}')"
echo "-------------------------------------------------------------------------"
echo "User: $(grep username /etc/kpanel/btsync.info | awk 'NR==1 {print $3}') | Password: $(grep password /etc/kpanel/btsync.info | awk 'NR==1 {print $3}')"
echo "-------------------------------------------------------------------------"
echo "BTsync phai duoc bat truoc khi truy cap ! "
/etc/kpanel/menu/17_bitsync/kpanel-bitsync-menu
fi
