#!/bin/sh
. /home/kpanel.conf
if [ -f /etc/cron.d/kpanel-auto-start-mysql.cron ]; then
/etc/kpanel/menu/tienich/kpanel-tat-auto-start-mysql
else
/etc/kpanel/menu/tienich/kpanel-bat-auto-start-mysql
fi

