#!/bin/bash 
. /home/kpanel.conf

if [ "$(iptables -L -n | grep :$priport | awk 'NR==1 {print $1}')" == "ACCEPT" ]; then
clear
echo "========================================================================="
echo "Port Phpmyadmin port ($priport) dang OPEN."
echo "-------------------------------------------------------------------------"
echo "Ban khong can mo lai no! " 
/etc/kpanel/menu/kpanel-phpmyadmin-menu
exit
fi

echo "========================================================================="
echo "Port ($priport) phai duoc mo neu ban muon truy cap Phpmyadmin, "
echo "-------------------------------------------------------------------------"
echo "Hay tai cac file qua port nay nhu: Backup files, Log files"
echo "-------------------------------------------------------------------------"
read -r -p "Ban muon mo port $priport ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "Please wait....";sleep 1
clear
echo "========================================================================="
	echo "Open phpmyadmin port ($priport) thanh cong !"
	echo "-------------------------------------------------------------------------"
	echo "Ban da co the truy cap phpmyadmin va download backup,log, CSR...files"
	echo "-------------------------------------------------------------------------"
	iptables -I INPUT -p tcp --dport $priport -j ACCEPT
	service iptables save
/etc/kpanel/menu/kpanel-phpmyadmin-menu
        ;;
    *)
        clear
echo "========================================================================="
echo "Ban huy OPEN Phpmyadmin Port (Port $priport)"
/etc/kpanel/menu/kpanel-phpmyadmin-menu
        ;;
esac

