#!/bin/sh
. /home/kpanel.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
clear
echo "========================================================================"
service nginx restart
/etc/kpanel/menu/tienich/kpanel-restart-service
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "kpanel trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
		echo "-------------------------------------------------------------------------"
service nginx start
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
		if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
clear
echo "========================================================================"
service nginx restart
/etc/kpanel/menu/tienich/kpanel-restart-service
		else
		clear
echo "========================================================================"
echo "kpanel can not start Nginx Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Rat tiec, kpanel khong the khoi dong lai duoc Nginx!"
	#echo "Sorry, Nginx is stopped. Please start it before use this function !"
	/etc/kpanel/menu/tienich/kpanel-restart-service
		fi
fi
fi
#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
clear
echo "========================================================================"
service nginx stop
service nginx start
/etc/kpanel/menu/tienich/kpanel-restart-service
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "kpanel trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
		echo "-------------------------------------------------------------------------"
systemctl restart nginx.service
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
clear
echo "========================================================================"
service nginx stop
service nginx start
/etc/kpanel/menu/tienich/kpanel-restart-service
		else
				clear
echo "========================================================================"
echo "kpanel can not start Nginx Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Rat tiec, kpanel khong the khoi dong lai duoc Nginx!"
	#echo "Sorry, kpanel can not restart nginx service !"
	/etc/kpanel/menu/tienich/kpanel-restart-service
		fi
fi
fi
