#!/bin/bash 

. /home/kpanel.conf
clear
echo "========================================================================="
echo "Your VPS  Virtualization:"
echo "-------------------------------------------------------------------------"
virt-what
/etc/kpanel/menu/kpanel-tien-ich
