#!/bin/bash
prompt="Lua chon cua ban (0-Thoat):"
options=( "Thay Password Root" "Fix Loi Chmod, Chown" "Find Top Largest Files & Folders" "Service Running & Ram Use" "Kiem Tra IP/Nameserver Website" \
"File Size Converter " "Kiem Tra Thong Tin Server" "Cai Dat Server Timezone" "Install / Remove Imagick" "Install / Remove Ioncube" "Cai Dat Htop" \
"Backup Config File & Vhost" "Thay Doi Port SSH Number" "Config SSH Timeout" "Block Exploits, SQL Injections" "Deny Run Script In Upload Folder" \
"Dat Mat Khau Bao Ve Folder" "BAT/TAT Email Thong Bao Login" "BAT/TAT Auto Run kpanel" "Canh Bao Full Disc Tren Menu" "Restart Service" "TocDo.net" \
"Varnish Cache" "Update All Website Wordpress" "Install Composer" "Go Bo (Remove) kpanel" )
printf "=========================================================================\n"
printf "                KPANEL - Quan Ly VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
printf "                           Tien Ich - Addons\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


	1) /etc/kpanel/menu/kpanel-doi-pass-root-vps;;
	2) /etc/kpanel/menu/tienich/kpanel-sua-loi-chown;;
	3) /etc/kpanel/menu/tienich/kpanel-xem-danh-sach-max-dung-luong-file-menu;;
	4) /etc/kpanel/menu/tienich/kpanel-dich-vu-dang-chay-va-ram-dung;;
	5) /etc/kpanel/menu/tienich/kpanel-tim-ip-nameserver-website;;
	6) /etc/kpanel/menu/kpanel-chuyen-doi-don-vi-file-size-convert;;
	7) /etc/kpanel/menu/tienich/kpanel-view-thong-tin-ip-vps;;
	8) clear && /etc/kpanel/menu/kpanel-thay-doi-thong-tin-thoi-gian;; 
	9) /etc/kpanel/menu/tienich/kpanel-before-imagick;;
	10) /etc/kpanel/menu/tienich/kpanel-before-ioncube;;
	11) /etc/kpanel/menu/tienich/kpanel-cai-dat-htop;;
	12) /etc/kpanel/menu/kpanel-sao-luu-sys;;
	13) /etc/kpanel/menu/thay-doi-port-ssh;;
	14) /etc/kpanel/menu/kpanel-bat-tat-ssh-time-out;;
	15) /etc/kpanel/menu/kpanel-block-exploits-sql-injections-menu;;
	16) /etc/kpanel/menu/kpanel-chan-run-script-trong-folder-upload-menu;;
	17) /etc/kpanel/menu/kpanel-dat-mat-khau-bao-ve-folder-website;;
	18) /etc/kpanel/menu/bat-tat-email-thong-bao-dang-nhap-server;;
	19) /etc/kpanel/menu/kpanel-bat-tat-tu-dong-chay-kpanel;;
	20) /etc/kpanel/menu/kpanel-config-canh-bao-dung-luong-disc-trong-free-it;;
	21) clear && /etc/kpanel/menu/tienich/kpanel-restart-service;;
	22) clear && /etc/kpanel/menu/tienich/toc-do-dot-net;;
	23) clear && /etc/kpanel/menu/varnish/install-varnish;;
	24) clear && /etc/kpanel/menu/tienich/update-wordpress-for-all-site;;
	25) clear && /etc/kpanel/menu/tienich/install-composer;;
	26) /etc/kpanel/menu/go-bo-scripts;;
#	23) clear && kpanel;;
	0) clear && kpanel;;


            *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac
done
