#!/bin/bash

. /home/kpanel.conf


saoluuiptables ()
{
iptables-save > /etc/kpanel/iptables.bak
echo "--------------------------------------------------------------------------"
echo "Please wait..."
sleep 1
clear
echo "========================================================================="
echo "Sao luu IPtables Firewall Rules hoan thanh!"
/etc/kpanel/menu/kpanel-iptables-firewall-manager-menu
}
if [ -f /etc/kpanel/iptables.bak ]; then
echo "--------------------------------------------------------------------------"
echo "Phat hien file back up cu cua IPtables Firewall"
echo "--------------------------------------------------------------------------"
read -r -p "Xoa file backup nay va tao file backup moi ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
	saoluuiptables
        ;;
    *)
    clear
    echo "========================================================================="
        echo "Ban da huy tao file backup moi"
        /etc/kpanel/menu/kpanel-iptables-firewall-manager-menu
        ;;
esac
else
echo "========================================================================="
echo "Su dung chuc nang nay de sao luu IPtables Rules cho server"
echo "--------------------------------------------------------------------------"
echo "Chuan bi sao luu IPtables Rules"
sleep 3
saoluuiptables
fi
