#!/bin/sh
echo "Please wait....";sleep 1
clear
echo "========================================================================="
echo "VPS Uptime: $(uptime | awk '{print $3,$4}' | sed 's/,/ /g')"
/etc/kpanel/menu/kpanel-check-thong-tin-server
