#!/bin/sh
echo "Please wait....";sleep 1
clear
echo "========================================================================="
echo "Authenication Failures: $(awk '{print}' /var/log/secure* | grep -i 'authentication failure' | wc -l)"
/etc/kpanel/menu/kpanel-check-thong-tin-server
