#!/bin/sh
. /home/kpanel.conf

if [ ! -f /var/spool/cron/root ]; then
/etc/kpanel/menu/crontab/kpanel-xoa-het-cronjob
exit
fi

if [ "$(grep "auto-start-mysql" /var/spool/cron/root | awk '{print $6}')" == "auto-start-mysql" ]; then
/etc/kpanel/menu/crontab/kpanel-xoa-het-cronjob-but-auto-start-mariadb
exit
fi
if [ "$(grep "auto-start-mysql" /var/spool/cron/root | awk '{print $6}')" == "" ]; then
/etc/kpanel/menu/crontab/kpanel-xoa-het-cronjob
exit
fi
clear
echo "we can find cronjob for you"
/etc/kpanel/menu/crontab/kpanel-cronjob-menu
exit
fi
