#!/bin/bash

echo "=========================================================================="
echo "chomod 755 menu... "
echo "=========================================================================="

find /etc/kpanel/menu -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/checkddos -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/crontab -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/CSF-Fiwall -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/database-example -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/downloadlog -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/memcache -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/menucheck -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/nang-cap-mariaDB -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/nangcap-php -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/opcache -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/pagespeed -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/swap -type f -exec chmod 755 {} \;
#find /etc/kpanel/menu/tienich -type f -exec chmod 755 {} \;

#for d in /opt/kdata_kpanel/script/kpanel/menu/*
for d in /etc/kpanel/menu/*
do
	if [ -d $d ]; then
		echo $d
		find $d -type f -exec chmod 755 {} \;
	fi
done
