#!/bin/bash
prompt="Lua chon cua ban (0-Thoat):"
options=("Tao Tai Khoan FTP Cho Website" "Vo Hieu Hoa Tai Khoan FTP" "Thay Mat Khau Tai Khoan FTP" "Xem Thong Tin FTP Cua Website" "Setup FTP Server Over TLS" )
printf "=========================================================================\n"
printf "                KPANEL - Quan Ly VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
printf "                           Quan Ly FTP Server \n"
printf "=========================================================================\n"
echo ""
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    1) /etc/kpanel/menu/kpanel-tao-ftp-user-cho-domain;;
    2) /etc/kpanel/menu/kpanel-xoa-ftp-user;;
    3) /etc/kpanel/menu/kpanel-thay-mat-khau-user-ftp;;
    4) /etc/kpanel/menu/kpanel-view-userftp-password;;
    5) /etc/kpanel/menu/ftp-server-install;;
    0) clear && kpanel;;
$(( ${#options[@]}+1 )) ) echo "";  clear && kpanel;;
     *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done
