#!/bin/sh

echo "Install git..."
sudo yum -y install git > /dev/null 2>&1

# update code
if [ -d /opt/kdata_kpanel ]; then
cd ~ ; cd /opt/kdata_kpanel && git pull origin main ; cd ~
#git pull origin master
#git pull origin
fi

cd ~

sleep 5

find /opt/kdata_kpanel/script/kpanel/menu -type f -exec chmod 755 {} \;
/opt/kdata_kpanel/script/kpanel/menu/git-clone-done

