#!/bin/sh

echo "-------------------------------------------------------------------------"
echo "Ok ! please wait check reset code from git..."

cd ~
if [ -d /opt/kdata_kpanel ]; then
rm -rf /opt/kdata_kpanel/*
rm -rf /opt/kdata_kpanel
sleep 5
fi

/etc/kpanel/menu/git-clone
sleep 1

clear
echo "========================================================================="
echo "Done! Reset code from git..."
/etc/kpanel/menu/kpanel-update-upgrade-service-menu
