#!/bin/sh
. /home/kpanel.conf
echo "Please wait..."; sleep 1
clear
echo "========================================================================="
echo "Thong tin user Root cua MySQL:"
echo "-------------------------------------------------------------------------"
echo "User: root"
echo "-------------------------------------------------------------------------"
echo "Password: $mariadbpass"
/etc/kpanel/menu/kpanel-them-xoa-database
