#!/bin/sh
. /home/kpanel.conf
if [ ! -f /etc/kpanel/net2ftpsite.info ]; then
clear
echo "========================================================================="
echo "Ban chua cai dat domain Net2FTP cho Server !"
/etc/kpanel/menu/kpanel-net2ftp-menu
exit
fi
echo "Please wait..."; sleep 1
net2ftpsite=$(cat /etc/kpanel/net2ftpsite.info)
clear
echo "========================================================================="
echo "Domain Net2FTP: $net2ftpsite"
/etc/kpanel/menu/kpanel-net2ftp-menu
