#!/bin/sh
. /home/kpanel.conf
if [ ! -f /etc/kpanel/uploadsite ]; then
clear
echo "========================================================================="
echo "Ban chua cai dat File Manager cho Server !"
/etc/kpanel/menu/kpanel-web-upload-menu
exit
fi
echo "Please wait..."; sleep 1
uploadsite=$(cat /etc/kpanel/uploadsite)
clear
echo "========================================================================="
echo "Domain cai dat File Manager cho Server: "
echo "-------------------------------------------------------------------------"
echo "http://$uploadsite "
/etc/kpanel/menu/kpanel-web-upload-menu
