#!/bin/sh
. /home/kpanel.conf
if [ ! -f /usr/local/bin/htpasswd.py ]; then
cp -r /etc/kpanel/menu/kpanel-tao-mat-khau-bao-ve-folder.py /usr/local/bin/htpasswd.py
chmod 755 /usr/local/bin/htpasswd.py
fi
if [ ! -f /etc/kpanel/pwprotect.default ]; then
echo "" > /etc/kpanel/pwprotect.default
fi
if [ ! -f /etc/cron.d/kpanel.code.cron ]; then
touch /etc/cron.d/kpanel.code.cron
fi
if [ ! -d /home/$mainsite/private_html/backup ]; then
mkdir -p /home/$mainsite/private_html/backup
fi
find /home/$mainsite/private_html/backup/ -name "*.zip*" > /tmp/vpssim_check_backup_code_size

numberfiles=$(cat /tmp/vpssim_check_backup_code_size | wc -l)
if [ ! "$numberfiles" = "0" ]; then
backupcodesize=$(du -ch $(cat /tmp/vpssim_check_backup_code_size) | tail -1 | cut -f 1)
else
backupcodesize=0KB
fi
rm -rf /tmp/*kpanel*
prompt="Lua chon cua ban (0-Thoat):"
options=("Backup Code 1 Website" "Backup Code All Website" "Tu Dong Backup Website" "Phuc Hoi Website" "Lay Link File Backup" "Xoa Tat Ca File Backup")
printf "=========================================================================\n"
printf "                KPANEL - Quan Ly VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
printf "                         Sao Luu & Phuc Hoi Code\n"
printf "=========================================================================\n"
printf "                       Total Backup Files Size: $backupcodesize \n"
printf "=========================================================================\n"
if [ "$(grep auth_basic_user_file /etc/nginx/conf.d/$mainsite.conf)" == "" ] ; then 
echo "Ban chua BAT tinh nang bao ve phpMyAdmin va cac file backup, ocp.php ..."
echo "-------------------------------------------------------------------------"
echo "Dung chuc nang [ BAT/TAT Bao Ve phpMyAdmin ] trong [ Quan Ly phpMyAdmin ]"
echo "-------------------------------------------------------------------------"
echo "de bat tinh nang nay."
echo "-------------------------------------------------------------------------"
echo "Thong bao nay se tu dong TAT sau khi ban hoan thanh cau hinh bao mat !"
echo "========================================================================="
echo""
fi
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1 ) /etc/kpanel/menu/kpanel-sao-luu-code;;
    2 ) /etc/kpanel/menu/kpanel-lan-luot-sao-luu-het-tat-ca-website;;
    #3 ) /etc/kpanel/menu/kpanel-sao-luu-home;; "Backup Folder Home" 
    3 ) /etc/kpanel/menu/kpanel-tu-dong-sao-luu-code-menu;;
    4 ) /etc/kpanel/menu/kpanel-phuc-hoi-website;;
    5 ) /etc/kpanel/menu/kpanel-lay-link-sao-luu-website-backup-menu;;
    #6 ) /etc/kpanel/menu/kpanel-link-tai-sao-luu-tat-ca-cac-site;; "Link File Backup Home" 
    6 ) /etc/kpanel/menu/kpanel-xoa-toan-bo-backup-website;;
    7 ) clear && kpanel;;
    0) clear && kpanel;;
    
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done

