#!/bin/sh
. /home/kpanel.conf
if [ "$(grep KDATA.VN /bin/kpanel)" != "" ]; then
clear
echo "========================================================================= "
echo "You are using Vietnamese Version"
echo "-------------------------------------------------------------------------"
echo "( Ban dang su dung ngon ngu Tieng Viet )"
/etc/kpanel/menu/kpanel-thay-doi-ngon-ngu-menu
exit
fi

echo "========================================================================= "
echo "Su dung chuc nang nay de thay doi ngon ngu kpanel sang tieng Viet"
echo "-------------------------------------------------------------------------"
echo "kpanel ho tro Tieng Anh & Tieng Viet"
echo "========================================================================= "
read -r -p "Ban muon thay doi ngon ngu kpanel sang Tieng Viet ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ... "
sleep 1
echo "-------------------------------------------------------------------------"
wget -q --no-check-certificate https://kdata.vn/script/kpanel/motd -O /etc/motd
wget -q --no-check-certificate https://kdata.vn/script/kpanel/kpanel -O /bin/kpanel && chmod +x /bin/kpanel
cd /etc/kpanel/
rm -rf /etc/kpanel/menu.zip
wget -q --no-check-certificate https://kdata.vn/script/kpanel/menu.zip

#Check menu.zip files

rm -rf /tmp/menu
unzip -q -o menu.zip -d /tmp
if [ ! -f /tmp/menu/kpanel-tien-ich ]; then
rm -rf /tmp/menu
clear
echo "========================================================================="
echo "There's an error in changing language process"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/kpanel/menu/kpanel-update-upgrade-service-menu
exit
fi
## Finish check menu.zip
rm -rf /tmp/menu
unzip -q -o menu.zip
rm -rf /etc/kpanel/menu.zip
cd
wget -q --no-check-certificate https://kdata.vn/script/kpanel/motd -O /etc/motd
download_main_menu () {
wget -q --no-check-certificate https://kdata.vn/script/kpanel/kpanel -O /bin/kpanel && chmod +x /bin/kpanel
}
download_main_menu
checkvpssim_mainmenu=`cat /bin/kpanel`
if [ -z "$checkvpssim_mainmenu" ]; then
download_main_menu
fi
find /etc/kpanel/menu -type f -exec chmod 755 {} \;
clear 
echo "========================================================================= "
echo "Change Language of kpanel to Vietnamese Finished"
echo "-------------------------------------------------------------------------"
echo "( Thay doi ngon ngu kpanel sang tieng Viet thanh cong )"
/etc/kpanel/menu/kpanel-thay-doi-ngon-ngu-menu
       ;;
    *)
        echo ""
        ;;
esac
clear
clear
echo "========================================================================="
echo "Cancel Change Language for kpanel"
echo "-------------------------------------------------------------------------"
echo "Huy bo thay doi ngon ngu cho kpanel"
/etc/kpanel/menu/kpanel-thay-doi-ngon-ngu-menu
