#!/bin/sh
. /home/kpanel.conf
if [ -f /etc/kpanel/uploadsite ]; then
uploadsite=$(cat /etc/kpanel/uploadsite)
 if [ ! -d /home/$uploadsite/public_html ]; then
rm -rf /etc/kpanel/uploadsite
 fi
fi

if [ -f /etc/kpanel/uploadsite ]; then
filemanagedomain=$(cat /etc/kpanel/uploadsite)
checkfilemanagedomainconfig=$(grep auth_basic /etc/nginx/conf.d/$filemanagedomain.conf)
if [ "$checkfilemanagedomainconfig" == "" ]; then
Protection=Disable
else
Protection=Enable
fi
fi


show_menu_filemanager () {
prompt="Lua chon cua ban (0-Thoat):"
options=("Setup File Manager" "Cau hinh Upload Max Filesize" "Bao Ve File Manager" "Thay User & Password Admin" "Thay Domain File Manager" "Remove File Manager")
printf "=========================================================================\n"
printf "                kpanel - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                               File Manager \n"
printf "=========================================================================\n"
if [ ! -f /etc/kpanel/uploadsite ]; then 
printf "                      File Manager: Not Install \n"
else
printf "               File Manager: Installed | Protection: $Protection\n"
fi
printf "=========================================================================\n"
if [ -f /etc/kpanel/uploadsite ]; then
filemanagedomain=$(cat /etc/kpanel/uploadsite)
printf "Link File Manager: http://$filemanagedomain\n"
printf "=========================================================================\n"
fi
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/kpanel/menu/kpanel-cai-dat-web-upload-manage;;
    #2) /etc/kpanel/menu/kpanel-tat-bat-web-manage;;
    #3) /etc/kpanel/menu/kpanel-hien-link-web-upload;;
    2) /etc/kpanel/menu/kpanel-change-upload-file-size-limit-file-manage;;
    3) /etc/kpanel/menu/kpanel-mat-khau-bao-ve-web-file-manage;;
    4) /etc/kpanel/menu/kpanel-thay-mat-khau-web-file-manage;;
    5) /etc/kpanel/menu/kpanel-thay-domain-web-file-manage;;
    6) /etc/kpanel/menu/kpanel-xoa-website-upload-site;;
    #7) clear && /bin/kpanel;;
    0) clear && /bin/kpanel;;
    
  *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done
}
check_nginx_service () {
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
show_menu_filemanager 
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "kpanel trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
service nginx start
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
		if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
show_menu_filemanager 
		else
				clear
echo "========================================================================"
echo "kpanel can not start Nginx Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Rat tiec, Nginx dang stopped. Hay bat len truoc khi dung chuc nang nay!"
	kpanel
		fi
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
show_menu_filemanager 
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "kpanel trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
systemctl start nginx.service
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
show_menu_filemanager 
		else
				clear
echo "========================================================================"
echo "kpanel can not start Nginx Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Rat tiec, Nginx dang stopped. Hay bat len truoc khi dung chuc nang nay!"
	kpanel
		fi
fi
fi
}
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
check_nginx_service
	else
clear
echo "========================================================================"
echo "PHP-FPM service is not running"
echo "------------------------------------------------------------------------"
echo "kpanel trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
	echo "-------------------------------------------------------------------------"
service php-fpm start
clear
echo "========================================================================"
echo "Check PHP-FPM service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
			if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
check_nginx_service
		else
		clear
echo "========================================================================"
echo "kpanel can not start PHP-FPM Service"
sleep 4 ;
	clear
	echo "========================================================================="
	#echo "Sorry, PHP-FPM stopped. Start it before use this function!"
	echo "Sorry, PHP-FPM dang stopped. Hay bat len truoc khi dung chuc nang nay!"
	kpanel
		fi
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
check_nginx_service
	else
clear
echo "========================================================================"
echo "PHP-FPM service is not running"
echo "------------------------------------------------------------------------"
echo "kpanel trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
	echo "-------------------------------------------------------------------------"
systemctl start php-fpm.service
clear
echo "========================================================================"
echo "Check PHP-FPM service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
check_nginx_service
		else
		clear
echo "========================================================================"
echo "kpanel can not start PHP-FPM Service"
sleep 4 ;
	clear
	echo "========================================================================="
	#echo "Sorry, PHP-FPM stopped. Start it before use this function!"
	echo "Sorry, PHP-FPM dang stopped. Hay bat len truoc khi dung chuc nang nay!"
	kpanel
		fi
fi
fi


