#!/bin/sh
. /home/kpanel.conf
if [ "$(grep kpanel.COM /bin/kpanel)" != "" ]; then
clear
echo "========================================================================= "
echo "You are using English Version"
/etc/kpanel/menu/kpanel-thay-doi-ngon-ngu-menu
exit
fi
echo "========================================================================= "
echo "Use this function to change language for kpanel"
echo "-------------------------------------------------------------------------"
echo "kpanel support EngLish & Vietnamese"
echo "========================================================================= "
read -r -p "You want to change kpanel language to English ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ... "
sleep 1
echo "-------------------------------------------------------------------------"

cd /etc/kpanel/
rm -rf /etc/kpanel/menu.zip
wget -q --no-check-certificate https://kdata.vn/script/kpanel/menu.zip

#Check menu.zip files

rm -rf /tmp/menu
unzip -q -o menu.zip -d /tmp
if [ ! -f /tmp/menu/kpanel-tien-ich ]; then
rm -rf /tmp/menu
clear
echo "========================================================================="
echo "There's an error in changing language process"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/kpanel/menu/kpanel-update-upgrade-service-menu
exit
fi
## Finish check menu.zip
rm -rf /tmp/menu
unzip -q -o menu.zip
rm -rf /etc/kpanel/menu.zip
cd
download_main_menu () {
#wget -q --no-check-certificate https://kpanel.com/script/kpanel/kpanel -O /bin/kpanel && chmod +x /bin/kpanel
wget -q --no-check-certificate https://github.com/kdatavn/kpanel-version-2/raw/main/script/kpanel/kpanel -O /bin/kpanel && chmod +x /bin/kpanel
}
download_main_menu
checkvpssim_mainmenu=`cat /bin/kpanel`
if [ -z "$checkvpssim_mainmenu" ]; then
download_main_menu
fi
#wget -q --no-check-certificate https://kpanel.com/script/kpanel/motd -O /etc/motd
wget -q --no-check-certificate https://github.com/kdatavn/kpanel-version-2/raw/main/script/kpanel/motd -O /etc/motd
find /etc/kpanel/menu -type f -exec chmod 755 {} \;
clear 
echo "========================================================================= "
echo "Change Language of kpanel to English Finished"
/etc/kpanel/menu/kpanel-thay-doi-ngon-ngu-menu
       ;;
    *)
        echo ""
        ;;
esac
clear
clear
echo "========================================================================="
echo "Cancel Change Language for kpanel"
/etc/kpanel/menu/kpanel-thay-doi-ngon-ngu-menu
