#!/bin/sh
. /home/kpanel.conf
echo "========================================================================="
echo "Dung chuc nang nay de BAT/TAT che do Auto backup database tren server"
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten Database [ENTER]: " 
read dataname
if [ "$dataname" = "" ]; then
clear
echo "========================================================================="
echo "Ban chua nhap ten database !"
/etc/kpanel/menu/kpanel-them-xoa-database
exit
fi
if [ ! -f /var/lib/mysql/$dataname/db.opt ]; then
clear
echo "========================================================================="
echo "Database: $dataname khong ton tai tren he thong"
/etc/kpanel/menu/kpanel-them-xoa-database
exit
fi
if [ "$(ls -1 /var/lib/mysql/$dataname | wc -l)" == 1 ]; then
clear
echo "========================================================================="
echo "Database $dataname chua co du lieu"
/etc/kpanel/menu/kpanel-them-xoa-database
exit
fi

rm -rf /tmp/databaseautobackup
echo "$dataname" > /tmp/databaseautobackup
if [ -f /bin/kpanel-backupdb-$dataname ]; then
 if [ -f /etc/cron.d/kpanel.db.cron ]; then
     if [ ! "$(grep kpanel-backupdb-$dataname /etc/cron.d/kpanel.db.cron)" == "" ]; then
     /etc/kpanel/menu/kpanel-TAT-tu-dong-sao-luu-database
     fi
 fi
fi 
 /etc/kpanel/menu/kpanel-BAT-tu-dong-sao-luu-database
