#!/bin/bash
prompt="Nhap lua chon cua ban (0-Thoat):"
if [ ! -f /usr/local/maldetect/conf.maldet ]; then
options=( "Scan 1 website" "Scan All websites" "View Last Scan Report" "Cai Dat Linux Malware Detect")
else
options=( "Scan 1 website" "Scan All websites" "View Last Scan Report" "Remove Linux Malware Detect")
fi
printf "=========================================================================\n"
printf "               KPANEL - Quan Ly VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
if [ ! -f /usr/local/maldetect/conf.maldet ]; then
printf "                Linux Malware Detect (LMD) - Not Install\n"
else
printf "                 Linux Malware Detect (LMD) - Installed \n"
fi
printf "=========================================================================\n"
printf "\n"
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


    
    1) /etc/kpanel/menu/kpanel-scan-website-maldet;;
    2) /etc/kpanel/menu/kpanel-scan-home-maldet;;
    3) /etc/kpanel/menu/kpanel-view-last-scan-report;;
    4) /etc/kpanel/menu/kpanel-befor-maldet-cai-dat;;
    5) clear && kpanel;;
    0) clear && kpanel;;
        *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done





