#!/bin/bash

. /home/kpanel.conf
clear
echo "========================================================================="
echo "Cai dat KPANEL phien ban tieng ANH tai https://github.com/kdatavn/kpanel-version-2"
kpanel
