#!/bin/sh
. /home/kpanel.conf
echo "-------------------------------------------------------------------------"
echo "Please wait..."; sleep 1
clear
echo "========================================================================="
echo "Ban Co The Truy Cap Vao Phpmyadmin Bang Link Duoi:"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport"
/etc/kpanel/menu/kpanel-phpmyadmin-menu
