#!/bin/sh
prompt="Nhap lua chon cua ban (0-Thoat):"
options=( "Thoat")
printf "=========================================================================\n"
printf "               KPANEL - Manage VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
printf "                      Backup & Restore Database\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1 ) /etc/kpanel/menu/kpanel-sao-luu-data;;
    2 ) /etc/kpanel/menu/kpanel-lan-luot-sao-luu-het-tat-ca-database;;
    3 ) /etc/kpanel/menu/kpanel-phuc-hoi-database-chon-dinh-dang;;
    4 ) /etc/kpanel/menu/kpanel-lay-link-sao-luu-database-backup-menu;;
    #5 ) /etc/kpanel/menu/kpanel-list-database-tren-vps;; "Danh Sach Database Tren Server"
    5 ) clear && /etc/kpanel/menu/kpanel-them-xoa-database;;
    0 ) clear && /etc/kpanel/menu/kpanel-them-xoa-database;;

    
    *) echo "Ban nhap sai, vui long nhap theo danh sach";continue;;

    esac

done
