#!/bin/bash
prompt="Lua chon cua ban (0-Thoat):"
options=( "Mo Port (INPUT)" "Close Port (INPUT)" "Kiem Tra Service Dung Port" "Sao Luu IPtables Rules" "Phuc Hoi IPtables Rules" "Xem IPtables Rules Hien Tai" )
printf "=========================================================================\n"
printf "                kpanel - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                       Quan Ly IPtables Firewall\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/kpanel/menu/tienich/kpanel-mo-port-ip-tables;;
    2) /etc/kpanel/menu/tienich/kpanel-dong-port-ip-tables;;
    3) /etc/kpanel/menu/tienich/kpanel-check-port-service;;
    4) /etc/kpanel/menu/tienich/kpanel-sao-luu-iptables;;
    5) /etc/kpanel/menu/tienich/kpanel-phuc-hoi-iptables;;
    6) /etc/kpanel/menu/tienich/kpanel-view-iptables-rules;;
    7) clear && /bin/kpanel;;
    0) clear && kpanel;;

            *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac
done










