#!/bin/bash 
. /home/kpanel.conf

uploadsite=$(cat /tmp/uploadsite)
check_folder_protect_config()
{
if [ -d /etc/nginx/pwprotect/$uploadsite ]; then
cd /etc/nginx/pwprotect/$uploadsite
rm -rf * .??*
cd
rm -rf /etc/nginx/pwprotect/$uploadsite
fi
}
check_ftp_account()
{
if [ ! -f /etc/kpanel/FTP-Account.info ]; then
echo "=========================================================================" > /etc/kpanel/FTP-Account.info
echo "Please Do Not Delete This File " >> /etc/kpanel/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/kpanel/FTP-Account.info
echo "If you delete this file, KPANEL will not run !" >> /etc/kpanel/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/kpanel/FTP-Account.info
echo "All FTP User for all domain on VPS list below:" >> /etc/kpanel/FTP-Account.info
echo "=========================================================================" >> /etc/kpanel/FTP-Account.info
echo "" >> /etc/kpanel/FTP-Account.info
fi
if [ -f /etc/pure-ftpd/pureftpd.passwd ]; then
if [ ! "$(grep /home/$uploadsite/ /etc/pure-ftpd/pureftpd.passwd)" == "" ];then  
rm -rf /tmp/abcd
cat > "/tmp/abcd" <<END	
sed -i '/\/home\/$uploadsite/d' /etc/pure-ftpd/pureftpd.passwd
END
chmod +x /tmp/abcd
/tmp/abcd
rm -rf /tmp/abcd
pure-pw mkdb
fi
fi
if [ ! "$(grep /home/$uploadsite/ /etc/kpanel/FTP-Account.info)" == "" ];then 
echo "========================================================================="
echo "Phat hien tai khoan FTP: $(grep /home/$uploadsite/ /etc/kpanel/FTP-Account.info | awk 'NR==1 {print $7}') cua $uploadsite  "
echo "-------------------------------------------------------------------------"
echo "KPANEL se remove tai khoan FTP: $(grep /home/$uploadsite/ /etc/kpanel/FTP-Account.info | awk 'NR==1 {print $7}')"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
echo "-------------------------------------------------------------------------"
sleep 6
rm -rf /tmp/abcde
cat > "/tmp/abcde" <<END	
sed -i '/\/home\/$uploadsite/d' /etc/kpanel/FTP-Account.info
END
chmod +x /tmp/abcde
/tmp/abcde
rm -rf /tmp/abcde
fi
}
echo "========================================================================="
echo "Domain ban muon remove la Domain File Manager"
echo "-------------------------------------------------------------------------"
read -r -p "Ban chac chan muon xoa domain nay khoi server ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait....";sleep 1
rm -rf /etc/kpanel/uploadsite
rm -rf /home/$uploadsite
rm -f /etc/nginx/conf.d/$uploadsite.conf 
if [ ! -f /etc/kpanel/opcache.blacklist ]; then
cat > "/etc/kpanel/opcache.blacklist" <<END
END
fi
if [ ! "$(grep /home/$uploadsite /etc/kpanel/opcache.blacklist)" == "" ]; then
echo "-------------------------------------------------------------------------"
echo "Phat hien $uploadsite trong Zend Opcache Blacklist"
echo "-------------------------------------------------------------------------"
echo "KPANEL se xoa $uploadsite trong blacklist nay"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 6
rm -rf /tmp/zendcacheblacklist
cat > "/tmp/zendcacheblacklist" <<END
sed --in-place '\/home\/$uploadsite/d' /etc/kpanel/opcache.blacklist
END
chmod +x /tmp/zendcacheblacklist
/tmp/zendcacheblacklist
rm -rf /tmp/zendcacheblacklist
fi
check_ftp_account
check_and_delete_auto_backup_website()
{
	if [  -f /bin/kpanel-backupcode-$uploadsite ]; then
	if [ ! "$(grep kpanel-backupcode-$uploadsite /etc/cron.d/kpanel.code.cron)" == "" ]; then
echo "========================================================================="
echo "Phat hien $uploadsite dang bat auto backup code"
echo "-------------------------------------------------------------------------"
echo "KPANEL se tat che do auto backup code khi remove khoi server"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 5
	rm -rf /bin/kpanel-backupcode-$uploadsite
	cat > "/tmp/removebackupcode" <<END
sed -i '/kpanel-backupcode-$uploadsite/d' /etc/cron.d/kpanel.code.cron
END
chmod +x /tmp/removebackupcode
/tmp/removebackupcode 
rm -rf /tmp/removebackupcode
service crond restart
	fi
	fi
}
check_and_delete_auto_backup_website
check_folder_protect_config
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi 
rm -rf /tmp/upload*
clear
echo "========================================================================= "
echo "Remove Domain File Manager thanh cong ! "
kpanel
;;
    *)
    rm -rf /tmp/upload*
       clear 
echo "========================================================================= "
echo "Ban huy remove Domain File Manager."
kpanel
        ;;
esac
rm -rf /tmp/upload*
clear 
echo "========================================================================= "
echo "Ban huy remove Domain File Manager"
kpanel



