#!/bin/sh

. /home/kpanel.conf
dataname=$(cat /tmp/databaseautobackup)

echo "-------------------------------------------------------------------------"
echo "Database $dataname dang duoc BAT che do Auto Backup"
echo "-------------------------------------------------------------------------"
read -r -p "Ban muon TAT Auto Backup cho database $dataname  ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait ..."
sleep 1
rm -rf /bin/kpanel-backupdb-$dataname
if [ -f /etc/cron.d/kpanel.db.cron ]; then
cat > "/tmp/removebackupdb" <<END
sed -i '/kpanel-backupdb-$dataname/d' /etc/cron.d/kpanel.db.cron
END
chmod +x /tmp/removebackupdb
/tmp/removebackupdb 
rm -rf /tmp/removebackupdb
service crond restart
fi
clear
echo "========================================================================="
echo "TAT che do tu dong backup Database cho $dataname thanh cong."
/etc/kpanel/menu/kpanel-them-xoa-database
        ;;
    *)
        clear
echo "========================================================================= "
echo "Huy TAT che do auto backup Database cho $dataname !"
/etc/kpanel/menu/kpanel-them-xoa-database
        ;;
esac
