#!/bin/bash 

. /home/kpanel.conf

echo "========================================================================="
echo "Su dung chuc nang nay de update Wordpress code len phien ban moi nhat"  
echo "-------------------------------------------------------------------------"
echo "Truoc khi update, kpanel tien hanh sao luu database cho website"
echo "========================================================================="
#prompt="Nhap lua chon cua ban: "
prompt="Lua chon cua ban: "
options=( "Update 1 website" "Update tat ca Wordpress website" "Huy bo")
printf "LUA CHON CACH UPDATE\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) luachonupdate="update1site"; break;;
    2) luachonupdate="updateall"; break;;
    3) chonphpversion="cancle"; break;;
    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;
    #*) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu";continue;;
    esac  
done
###################################
#Update 1 website
###################################
if [ "$luachonupdate" = "update1site" ]; then
/etc/kpanel/menu/kpanel-update-wordpresss-code-for-website
###################################
#Update tat ca cac website
###################################
elif [ "$luachonupdate" = "updateall" ]; then
/etc/kpanel/menu/kpanel-update-wp-code-tat-ca-vps-website-wordpress
###################################
#Huy bo update
###################################
else 
clear && /etc/kpanel/menu/kpanel-wordpress-tools-menu
fi
