#!/bin/bash

clear
echo "========================================================================="
echo "---------------------------- kpanel -------------------------------"
if [ -f /etc/kpanel/kpanel.version ]; then
echo "kpanel version: "$(cat /etc/kpanel/kpanel.version)
fi
echo "------------------------------ PHP --------------------------------"
echo "PHP version: "$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")
echo "------------------------- phpmyadmin ------------------------------"
if [ -f /etc/kpanel/phpmyadmin.version ]; then
echo "phpmyadmin version: "$(cat /etc/kpanel/phpmyadmin.version)
fi
echo "------------------------------ LDD --------------------------------"
ldd --version
echo "----------------------------- nginx -------------------------------"
nginx -V
echo "---------------------------- openssl ------------------------------"
openssl version
echo "========================================================================="

/etc/kpanel/menu/kpanel-update-upgrade-service-menu
