#!/bin/bash
. /home/kpanel.conf

if [ ! -f /etc/kpanel/kpanel.version ]; then
clear
echo "========================================================================="
echo "Xin loi, chung toi khong the biet phien ban hien tai cua ban"
echo "-------------------------------------------------------------------------"
echo "Hay chac rang ban chay script offical tu website https://github.com/kdatavn/kpanel-version-2"
kpanel
exit
fi

maximumsize=10
rm -rf /etc/kpanel/kpanel.newversion
cd /etc/kpanel
#timeout 3 wget -q http://hostingaz.vn/script/kpanel/kpanel.newversion
timeout 3 wget --no-check-certificate -q https://raw.githubusercontent.com/kdatavn/kpanel-version-2/main/version -O /etc/kpanel/kpanel.newversion

cd
if [ -f /etc/kpanel/kpanel.newversion ]; then
checksizeversion=$(du -sb /etc/kpanel/kpanel.newversion | awk 'NR==1 {print $1}')
if [ "$checksizeversion" == "0" ];then
rm -rf /etc/kpanel/kpanel.newversion
fi
if [ $checksizeversion -gt $maximumsize ]; then
rm -rf /etc/kpanel/kpanel.newversion
fi
fi

if [ ! -f /etc/kpanel/kpanel.newversion ]; then
clear
printf "=========================================================================\n"
echo "Khong the kiem tra phien ban update KPANEL"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai"
/etc/kpanel/menu/kpanel-update-upgrade-service-menu
else
LOCALVER=`cat /etc/kpanel/kpanel.version`
REMOVER=`cat /etc/kpanel/kpanel.newversion`
fi


chuaCoBanMoi="n"
if [ "$LOCALVER" == "$REMOVER" ]; then
clear
rm -rf /etc/kpanel/kpanel.newversion
echo "========================================================================="
echo "Ban dang su dung phien ban moi nhat cua KPANEL - Phien ban: $LOCALVER"
echo "-------------------------------------------------------------------------"
echo "Xem KPANEL update Log tai: https://github.com/kdatavn/kpanel-version-2"

echo -n "Ban van muon cap nhat lai KPANEL chu? [y/N] "
read vanCapNhat
if [ "$vanCapNhat" = "y" ]; then
echo "OK sir! tien trinh cap nhat se duoc tiep tuc..."
sleep 3
chuaCoBanMoi="y"
else
/etc/kpanel/menu/kpanel-update-upgrade-service-menu
exit
fi
fi

printf "=========================================================================\n"
printf "Xem KPANEL update Log tai: https://github.com/kdatavn/kpanel-version-2\n"
printf "=========================================================================\n"
printf "Da phat hien update cho KPANEL\n"
echo "-------------------------------------------------------------------------"
printf "Phien ban ban dang su dung: $LOCALVER\n"
echo "-------------------------------------------------------------------------"
printf "Phien ban ban moi nhat tai thoi diem hien tai: $REMOVER\n"
printf "=========================================================================\n"

if [ "$chuaCoBanMoi" = "y" ]; then
response="y"
else
read -r -p "Ban chac chan muon update KPANEL ? [y/N] " response
fi

if [ "$response" = "y" ] || [ "$response" = "Y" ]; then
echo "-------------------------------------------------------------------------" 
echo "Chuan bi update KPANEL..... "
sleep 1

rm -rf /etc/kpanel/kpanel-update
#wget -q http://hostingaz.vn/script/kpanel/kpanel-update -O /etc/kpanel/kpanel-update && chmod +x /etc/kpanel/kpanel-update
wget --no-check-certificate -q https://raw.githubusercontent.com/kdatavn/kpanel-version-2/main/script/kpanel/kpanel-update -O /etc/kpanel/kpanel-update
chmod +x /etc/kpanel/kpanel-update
bash /etc/kpanel/kpanel-update

else

clear
printf "=========================================================================\n"
echo "Ban da huy bo update KPANEL"
/etc/kpanel/menu/kpanel-update-upgrade-service-menu

fi

#
clear && /etc/kpanel/menu/kpanel-update-upgrade-service-menu

exit
