#!/bin/bash

# Download init & config file for nginx
rm -f /etc/init.d/nginx
download_initd_nginx () {
#wget --no-check-certificate -q https://kpanel.echbay.com/script/kpanel/nginx -O /etc/init.d/nginx && chmod +x /etc/init.d/nginx
yes | cp -rf /opt/kdata_kpanel/script/kpanel/nginx /etc/init.d/nginx && chmod +x /etc/init.d/nginx
}
download_initd_nginx
checkdownload_initd_nginx=`cat /etc/init.d/nginx`
if [ -z "$checkdownload_initd_nginx" ]; then
download_initd_nginx
fi
chmod +x /usr/sbin/nginx
rm -rf /etc/nginx/nginx.conf
mv /tmp/nginx.conf /etc/nginx/nginx.conf

echo "=========================================================================="
echo "Cai Dat Hoan Tat Nginx "
echo "=========================================================================="
#exit
nginx -V

# End Download init & config file for nginx
