#!/bin/bash
current_os_version=$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))
#echo $current_os_version

if [ "$current_os_version" == "6" ] || [ "$current_os_version" == "7" ]; then
	sudo yum -y install psmisc bc gawk gcc
	sudo yum -y -q install virt-what unzip sudo net-tools iproute iproute2 curl deltarpm yum-utils tar
	sudo yum -y install epel-release
else
	sudo dnf -y install psmisc bc gawk gcc
	sudo dnf -y -q install virt-what unzip sudo net-tools iproute curl dnf-utils tar
	sudo dnf -y install epel-release
	dnf repolist
	dnf config-manager --set-enabled PowerTools
fi

