#!/bin/bash 
. /home/kpanel.conf
if [ -f /etc/kpanel/netdatasite.info ]; then
clear
echo "========================================================================="
echo "Ban da cai dat Netdata cho server !"
echo "-------------------------------------------------------------------------"
echo "Domain Netdata la: $(cat /etc/kpanel/netdatasite.info)"
echo "-------------------------------------------------------------------------"
echo "Hay tro $(cat /etc/kpanel/netdatasite.info) toi $serverip"
echo "-------------------------------------------------------------------------"
echo "va truy cap domain nay tren trinh duyet de su dung NetData"
/etc/kpanel/menu/22_netdata/kpanel-netdata-menu
exit
fi

#checkketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://kpanel.com/script/kpanel/Softwear/00-all-netdata-version.txt" )
checkketnoi=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://raw.githubusercontent.com/kdatavn/kpanel-version-2/main/script/kpanel/Softwear/00-all-netdata-version.txt" )
if [[ "$checkketnoi" == "000" ]]; then
clear
echo "========================================================================="
echo "Can not check NetData version"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/kpanel/menu/22_netdata/kpanel-netdata-menu
exit
fi

cd /tmp
download_version_netdata () {
#wget --no-check-certificate -q https://kpanel.com/script/kpanel/Softwear/00-all-netdata-version.txt
wget --no-check-certificate -q https://raw.githubusercontent.com/kdatavn/kpanel-version-2/main/script/kpanel/Softwear/00-all-netdata-version.txt
}
download_version_netdata
checkdownload_version_netdata=`cat /tmp/00-all-netdata-version.txt`
if [ -z "$checkdownload_version_netdata" ]; then
download_version_netdata
fi
cd
NetData_VERSION=`cat /tmp/00-all-netdata-version.txt | awk 'NR==2 {print $1}' | sed 's/|//' | sed 's/|//'`
echo "========================================================================="
echo "Su dung chuc nang nay de cai dat NetData cho server"
echo "-------------------------------------------------------------------------"
echo "Domain cho NetData phai la domain moi, chua duoc add vao he thong"
echo "-------------------------------------------------------------------------"
echo "Ban nen su dung Sub-domain cho NetData."
echo "-------------------------------------------------------------------------"
echo -n "Nhap ten Domain [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "Ban nhap sai, vui long nhap lai!"
/etc/kpanel/menu/22_netdata/kpanel-netdata-menu
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website co le khong phai la domain !!"
echo "-------------------------------------------------------------------------"
echo "Ban vui long thu lai  !"
/etc/kpanel/menu/22_netdata/kpanel-netdata-menu
exit
fi

if [ -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Phat hien $website da ton tai tren he thong!"
/etc/kpanel/menu/22_netdata/kpanel-netdata-menu
exit
fi
backend=kpanel-`date |md5sum |cut -c '1-12'`
echo "========================================================================="
echo "Chuan bi cai dat NetData cho $website"
echo "-------------------------------------------------------------------------"
echo "De bao mat, cac Search Engine se bi chan khi ket noi toi $website" 
echo "-------------------------------------------------------------------------"
echo "$website se khong xuat hien tren Google, bing..."
echo "-------------------------------------------------------------------------"
echo "De bao mat, ban khong the truy cap http://$serverip:19999 cho NetData."
echo "-------------------------------------------------------------------------"
echo "please wait... "; sleep 8
yum -y install libuuid-devel uuid-dev zlib-devel zlib1g-dev autoconf automake pkg-config
cd /usr/local/kpanel
rm -rf netdata
#wget --no-check-certificate -q https://kpanel.com/script/kpanel/Softwear/netdata_$NetData_VERSION.zip
wget --no-check-certificate -q https://github.com/kdatavn/kdata-vps-software/raw/master/netdata_$NetData_VERSION.zip
unzip -o -q netdata_$NetData_VERSION.zip
rm -rf /usr/local/kpanel/netdata_$NetData_VERSION.zip
cd /usr/local/kpanel/netdata
yes "" | ./netdata-installer.sh
cd
sed -i "s/.*# bind to =.*/    bind to = 127.0.0.1/g" /etc/netdata/netdata.conf
sed -i "s/.*access log =.*/    access log = none/g" /etc/netdata/netdata.conf
    cat > "/etc/nginx/conf.d/$website.conf" <<END
upstream $backend {
    server 127.0.0.1:19999;
    keepalive 64;
}
 
server {
    server_name $website;
    location / {
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Server \$host;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_pass http://$backend;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
error_page 502  /502.html;
        location = /502.html {
                root /etc/netdata;
                internal;
        }
}

END
echo "<br><br><br><br><br><br><br><b><center> Please enable NetData to view this page !</center></b>" > /etc/netdata/502.html
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
# stop netdata
killall netdata
# copy netdata to init.d
cp /usr/local/kpanel/netdata/system/netdata-init-d /etc/init.d/netdata && chmod +x /etc/init.d/netdata
# enable netdata at boot
chkconfig --add netdata
chkconfig --levels 235 netdata on
# start netdata
service netdata start
service netdata restart
# reload nginx
service nginx reload
else 
# stop netdata
killall netdata
# copy netdata.service to systemd
cp /usr/local/kpanel/netdata/system/netdata.service /etc/systemd/system/ && chmod +x /etc/systemd/system/netdata.service
# let systemd know there is a new service
systemctl daemon-reload
# enable netdata at boot
systemctl enable netdata
# start netdata
systemctl start netdata
service netdata start
service netdata restart
# reload nginx
systemctl reload nginx
fi
echo "$website" > /etc/kpanel/netdatasite.info
echo "$NetData_VERSION" > /etc/kpanel/netdata.version
rm -rf /tmp/00-all-netdata-version.txt
clear

echo "========================================================================="
echo "Cai dat NetData $NetData_VERSION cho $website thanh cong"
echo "-------------------------------------------------------------------------"
echo "Hay tro $website toi $serverip"
echo "-------------------------------------------------------------------------"
echo "va truy cap domain nay tren trinh duyet de su dung NetData"
/etc/kpanel/menu/22_netdata/kpanel-netdata-menu
