#!/bin/sh

curTime=$(date +%d)
#echo "curTime: "$curTime


if [ ! -f /tmp/kpanel.newversion ]; then
touch -a -m -t 201602180130.09 /tmp/kpanel.newversion  
fi

fileTime2=$(date -r /tmp/kpanel.newversion +%d)
#echo "fileTime2: "$fileTime2

if [ ! "$fileTime2" == "$curTime" ]; then
rm -rf /tmp/kpanel.newversion
#wget -q https://kpanel.echbay.com/script/kpanel/kpanel.newversion -O /tmp/kpanel.newversion
wget --no-check-certificate -q https://raw.githubusercontent.com/kdatavn/kpanel-version-2/main/version -O /tmp/kpanel.newversion
touch /tmp/kpanel.newversion
LOCALVER=`cat /etc/kpanel/kpanel.version`
checksize=$(du -sb /tmp/kpanel.newversion | awk 'NR==1 {print $1}')
###
	if [ $checksize -gt 2 ]; then
	REMOVER=`cat /tmp/kpanel.newversion`
	cat >> "/tmp/kpanel_check_kpanel_version" <<END
		if [ ! "$LOCALVER" == "$REMOVER" ]; then
			echo "========================================================================="
			echo "Update for KPANEL found !  "
			echo "-------------------------------------------------------------------------"
			echo "Your Version: $LOCALVER   |   Newest version: $REMOVER"
			echo "-------------------------------------------------------------------------"
			echo "How to update: KPANEL menu => Update System => Update KPANEL "
			
		fi
END
	chmod +x /tmp/kpanel_check_kpanel_version
	/tmp/kpanel_check_kpanel_version
	rm -rf /tmp/kpanel_check_kpanel_version
	fi
fi



