#!/bin/bash
if [ -f /swapfile ]; then
echo "========================================================================="
echo "Chuc nang nay chi ho tro xoa Swap do kpanel tao ra truoc do"
echo "-------------------------------------------------------------------------"
echo "Voi Swap co san tren he thong, kpanel khong the can thiep duoc"
echo "========================================================================="
read -r -p "Ban muon xoa swap tren server? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 1
swapoff /swapfile
rm -rf /swapfile
clear
echo "========================================================================= "
echo "Ban xoa swap thanh cong.  "
echo "-------------------------------------------------------------------------"
echo "Bay gio ban co the tao swap moi! "
/etc/kpanel/menu/swap/kpanel-them-xoa-swap-vps-menu

;;
    *)
       clear
echo "========================================================================= "
echo "Ban huy bo xoa SWAP."
/etc/kpanel/menu/swap/kpanel-them-xoa-swap-vps-menu
        ;;
esac
clear
/etc/kpanel/menu/swap/kpanel-them-xoa-swap-vps-menu
else
clear
echo "========================================================================= "
echo "Ban chua tao swap tren VPS !"
echo "-------------------------------------------------------------------------"
echo "Hoac VPS khong ho tro ban tao them SWAP."
/etc/kpanel/menu/swap/kpanel-them-xoa-swap-vps-menu
exit
fi
