#!/bin/sh
. /home/kpanel.conf
if [ ! "$(redis-cli ping)" = "PONG" ]; then
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service redis start
else 
systemctl start redis.service
fi
clear
/etc/kpanel/menu/redis/kpanel-install-redis
else
/etc/kpanel/menu/redis/kpanel-remove-redis
fi

