#!/bin/sh
. /home/kdata.conf

prompt="Nhap lua chon cua ban: "
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
if [ "$(/sbin/service redis status | awk 'NR==1 {print $5}')" == "running..." ]; then
options=("Disable Redis Cache" "Clear Redis Cache" "Cau hinh Redis Cache" "Kiem tra Redis Status" "Remove Redis Cache")
redistatus=Working
fi
if [ "$(/sbin/service redis status | awk 'NR==1 {print $3}')" == "stopped" ]; then
options=("Enable Redis Cache" "Clear Redis Cache" "Cau hinh Redis Cache" "Kiem tra Redis Status" "Remove Redis Cache")
redistatus=Stopped
fi
fi
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
if [ "`systemctl is-active redis.service`" == "active" ]; then
options=("Disable Redis Cache" "Clear Redis Cache" "Cau hinh Redis Cache" "Kiem tra Redis Status" "Remove Redis Cache")
redistatus=Working
else
options=("Enabled Redis Cache" "Clear Redis Cache" "Cau hinh Redis Cache" "Kiem tra Redis Status" "Remove Redis Cache")
redistatus=Stopped
fi
fi
printf "=========================================================================\n"
printf "                KPANEL - Quan Ly VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
printf "                           Quan Ly Redis Cache                                \n"
printf "=========================================================================\n"
printf "          Redis: $redistatus - Ram Max: $(grep maxmemory /etc/redis/redis.conf | awk 'NR==1 {print $2}' | sed 's/mb//') M "
if [ "`systemctl is-active redis.service`" == "active" ]; then
printf " - Ram Using: $(redis-cli INFO | grep used_memory_human | sed 's/used_memory_human://') \n"
else
printf "\n"
fi
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in

    1) /etc/kdata/menu/redis/kdata-before-bat-tat-redis;;
    2) /etc/kdata/menu/redis/kdata-clear-redis;;
    3) /etc/kdata/menu/redis/kdata-redis-change-size;;
    4) /etc/kdata/menu/redis/kdata-check-redis-status;;
    5) /etc/kdata/menu/redis/kdata-install-remove-redis;;

$(( ${#options[@]}+1 )) ) echo "";  clear && /bin/kdata;;
     *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done

