#!/bin/bash
if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi
prompt="Lua chon cua ban (0-Thoat):"
options=("Tao Tai Khoan FTP Cho Website" "Vo Hieu Hoa Tai Khoan FTP" "Thay Mat Khau Tai Khoan FTP" "Xem Thong Tin FTP Cua Website" "Remove FTP Server" )
printf "=========================================================================\n"
printf "                kpanel - Quan Ly VPS/Server by HostingAZ.VN \n"
printf "=========================================================================\n"
printf "                            Quan Ly FTP Server \n"
printf "=========================================================================\n"
echo ""
PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
    
        1) /etc/kpanel/menu/ftpserver/kpanel-tao-ftp-user-cho-domain;;
    2) /etc/kpanel/menu/ftpserver/kpanel-xoa-ftp-user;;
    3) /etc/kpanel/menu/ftpserver/kpanel-thay-mat-khau-user-ftp;;
    4) /etc/kpanel/menu/ftpserver/kpanel-view-userftp-password;;
       5) /etc/kpanel/menu/ftpserver/ftp-server-remove;;
    0) clear && kpanel;;

$(( ${#options[@]}+1 )) ) echo "";  clear && kpanel;;
     *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done


