#!/bin/sh
. /home/kpanel.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/kpanel/menu/memcache/kpanel-tat-memcache
exit
fi
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
/etc/kpanel/menu/memcache/kpanel-bat-memcache
clear
exit
fi
fi

#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "`systemctl is-active memcached.service`" == "active" ]; then
clear
/etc/kpanel/menu/memcache/kpanel-tat-memcache
exit
fi
if [ ! "`systemctl is-active memcached.service`" == "active" ]; then
clear
/etc/kpanel/menu/memcache/kpanel-bat-memcache
exit
fi
fi
clear
echo "========================================================================="
echo "Sorry, KPANEL khong phat hien Memcached tren he thong !"
kpanel
exit
fi

