#!/bin/bash
. /home/kpanel.conf
prompt="Nhap lua chon cua ban:"
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
options=("Install Memcached" )
fi
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
options=("Install Memcached" )
fi
fi
#if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then
if [ ! "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then
if [ ! "`systemctl is-active memcached.service`" == "active" ]; then
options=("Install Memcached" )
fi
fi
printf "=========================================================================\n"
printf "                KDATA - Quan Ly VPS/Server by KDATA.VN \n"
printf "=========================================================================\n"
printf "                           Memcached Manage \n"
printf "=========================================================================\n"
printf "Link Memcached Manage: http://$serverip:$priport/memcache.php\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" "Thoat"; do

    case "$REPLY" in

    1 ) /etc/kpanel/menu/memcache/kpanel-install-remove-memcache;;


$(( ${#options[@]}+1 )) ) echo "";  clear && /bin/kpanel;;
     *) echo "Ban nhap sai, vui long nhap theo so thu tu tren menu !";continue;;

    esac

done
