#!/bin/bash
clear
echo "-------------------------------------------------------------------------"
echo "Bat dau go cai dat Memcached"
echo "Please wait....";sleep 1
yum -y remove memcache*
clear
echo "========================================================================= "
echo "Go cai dat Memcached thanh cong."
/etc/kpanel/menu/memcache/kpanel-before-memcache-menu
