#!/bin/bash

. /home/kpanel.conf

if [ ! -f /etc/kpanel/net2ftpsite.info ]; then
clear
echo "========================================================================="
echo "Ban chua cai dat domain Net2FTP cho Server !"
/etc/kpanel/menu/21_net2ftp/kpanel-net2ftp-menu
exit
fi
net2ftpsite=$(cat /etc/kpanel/net2ftpsite.info)

if [ ! -f /etc/nginx/conf.d/$net2ftpsite.conf ]; then
clear
echo "========================================================================="
echo "KPANEL khong the xoa domain $net2ftpsite !"
/etc/kpanel/menu/21_net2ftp/kpanel-net2ftp-menu
exit
fi

if [ ! -d /home/$net2ftpsite/public_html ]; then
clear
echo "========================================================================="
echo "KPANEL khong the xoa domain $net2ftpsite !"
/etc/kpanel/menu/21_net2ftp/kpanel-net2ftp-menu
exit
fi

check_folder_protect_config()
{
if [ -d /etc/nginx/pwprotect/$net2ftpsite ]; then
cd /etc/nginx/pwprotect/$net2ftpsite
rm -rf * .??*
cd
rm -rf /etc/nginx/pwprotect/$net2ftpsite
fi
}

check_ftp_account()
{
if [ ! -f /etc/kpanel/FTP-Account.info ]; then
echo "=========================================================================" > /etc/kpanel/FTP-Account.info
echo "Please Do Not Delete This File " >> /etc/kpanel/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/kpanel/FTP-Account.info
echo "If you delete this file, kpanel will not run !" >> /etc/kpanel/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/kpanel/FTP-Account.info
echo "All FTP User for all domain on VPS list below:" >> /etc/kpanel/FTP-Account.info
echo "=========================================================================" >> /etc/kpanel/FTP-Account.info
echo "" >> /etc/kpanel/FTP-Account.info
fi
if [ -f /etc/pure-ftpd/pureftpd.passwd ]; then
if [ ! "$(grep /home/$net2ftpsite/ /etc/pure-ftpd/pureftpd.passwd)" == "" ];then  
rm -rf /tmp/abcd
cat > "/tmp/abcd" <<END	
sed -i '/\/home\/$net2ftpsite/d' /etc/pure-ftpd/pureftpd.passwd
END
chmod +x /tmp/abcd
/tmp/abcd
rm -rf /tmp/abcd
pure-pw mkdb
fi
fi
if [ ! "$(grep /home/$net2ftpsite/ /etc/kpanel/FTP-Account.info)" == "" ];then 
echo "========================================================================="
echo "Phat hien tai khoan FTP: $(grep /home/$net2ftpsite/ /etc/kpanel/FTP-Account.info | awk 'NR==1 {print $7}') cua $net2ftpsite  "
echo "-------------------------------------------------------------------------"
echo "KPANEL se remove tai khoan FTP: $(grep /home/$net2ftpsite/ /etc/kpanel/FTP-Account.info | awk 'NR==1 {print $7}')"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
echo "-------------------------------------------------------------------------"
sleep 6
rm -rf /tmp/abcde
cat > "/tmp/abcde" <<END	
sed -i '/\/home\/$net2ftpsite/d' /etc/kpanel/FTP-Account.info
END
chmod +x /tmp/abcde
/tmp/abcde
rm -rf /tmp/abcde
fi
}
echo "========================================================================="
read -r -p "Ban chac chan muon xoa domain Net2FTP ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait....";sleep 1
rm -rf /home/$net2ftpsite
rm -f /etc/nginx/conf.d/$net2ftpsite.conf 
if [ ! -f /etc/kpanel/opcache.blacklist ]; then
cat > "/etc/kpanel/opcache.blacklist" <<END
END
fi
if [ ! "$(grep /home/$net2ftpsite /etc/kpanel/opcache.blacklist)" == "" ]; then
echo "-------------------------------------------------------------------------"
echo "Phat hien $net2ftpsite trong Zend Opcache Blacklist"
echo "-------------------------------------------------------------------------"
echo "KPANEL se xoa $net2ftpsite trong blacklist nay"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 6
rm -rf /tmp/zendcacheblacklist
cat > "/tmp/zendcacheblacklist" <<END
sed --in-place '\/home\/$net2ftpsite/d' /etc/kpanel/opcache.blacklist
END
chmod +x /tmp/zendcacheblacklist
/tmp/zendcacheblacklist
rm -rf /tmp/zendcacheblacklist
fi
check_ftp_account
check_and_delete_auto_backup_website()
{
	if [  -f /bin/kpanel-backupcode-$net2ftpsite ]; then
	if [ ! "$(grep kpanel-backupcode-$net2ftpsite /etc/cron.d/kpanel.code.cron)" == "" ]; then
echo "========================================================================="
echo "Phat hien $net2ftpsite dang bat auto backup code"
echo "-------------------------------------------------------------------------"
echo "KPANEL se tat che do auto backup code khi remove khoi server"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 5
	rm -rf /bin/kpanel-backupcode-$net2ftpsite
	cat > "/tmp/removebackupcode" <<END
sed -i '/kpanel-backupcode-$net2ftpsite/d' /etc/cron.d/kpanel.code.cron
END
chmod +x /tmp/removebackupcode
/tmp/removebackupcode 
rm -rf /tmp/removebackupcode
service crond restart
	fi
	fi
}
check_and_delete_auto_backup_website
check_folder_protect_config
rm -rf /etc/kpanel/net2ftpsite.info
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi 
clear
echo "========================================================================= "
echo "Remove Domain Net2FTP thanh cong ! "
/etc/kpanel/menu/21_net2ftp/kpanel-net2ftp-menu
;;
    *)
       clear 
echo "========================================================================= "
echo "Ban huy remove Domain Net2FTP."
/etc/kpanel/menu/21_net2ftp/kpanel-net2ftp-menu
        ;;
esac
clear 
echo "========================================================================= "
echo "Ban huy remove Domain Net2FTP"
/etc/kpanel/menu/21_net2ftp/kpanel-net2ftp-menu



