#!/bin/sh
. /home/kpanel.conf
if [ ! -f /etc/php.ini ]; then
clear
echo "========================================================================="
echo "kpanel khong tim thay php.ini tren server"
/etc/kpanel/menu/config-php/kpanel-config-php.ini-menu
exit
fi

if [ "$(cat /etc/php.ini | grep display_errors | awk '{print $3}')" == "" ]; then
clear
echo "========================================================================="
echo "kpanel khong the thuc hien chuc nang nay"
/etc/kpanel/menu/config-php/kpanel-config-php.ini-menu
exit
fi

if [ "$(cat /etc/php.ini | grep display_errors | awk '{print $3}')" == "Off" ]; then
/etc/kpanel/menu/config-php/kpanel-dang-tat-display_errors
fi
if [ "$(cat /etc/php.ini | grep display_errors | awk '{print $3}')" == "On" ]; then
/etc/kpanel/menu/config-php/kpanel-dang-bat-display_errors
fi
}

