#!/bin/bash

if [ ! -f /etc/kpanel/varnish.version ]; then
touch /etc/kpanel/varnish.version
fi

chown -R root:root /etc/kpanel/varnish.version
chmod 644 /etc/kpanel/varnish.version
> /etc/kpanel/varnish.version
